name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    name: Type-check & Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Install dependencies
        run: npm install

      - name: Type-check
        run: npx tsc --noEmit

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_RPC_URL: https://soroban-testnet.stellar.org
          NEXT_PUBLIC_NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
          NEXT_PUBLIC_FACTORY_CONTRACT_ID: PLACEHOLDER
          NEXT_PUBLIC_HORIZON_URL: https://horizon-testnet.stellar.org
